/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.awt.GridLayout;
import java.awt.event.ActionListener;
import java.awt.event.KeyListener;
import java.awt.event.MouseAdapter;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Samsung
 */
public class VistaBatalla extends javax.swing.JFrame {

    /**
     * Creates new form VistaTerreno2
     */
    public VistaBatalla() {
        initComponents();
        setLocationRelativeTo(null);
        
        
        this.panelTerreno.setLayout(new GridLayout(15,15));
        for (int i=0;i<15;i++){
            for (int j=0;j<15;j++){
                botones [i][j]= new JButton();
                botones [i][j].setIcon(null);
                botones [i][j].setBorderPainted(true);
                this.panelTerreno.add(botones[i][j]); 
            }
        
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTerreno = new javax.swing.JPanel();
        btnInvocar = new javax.swing.JButton();
        btnFinalizar = new javax.swing.JButton();
        btnMover = new javax.swing.JButton();
        btnLanzar = new javax.swing.JButton();
        btnMagia = new javax.swing.JButton();
        btnTrampa = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        jProgressBar2 = new javax.swing.JProgressBar();
        jProgressBar3 = new javax.swing.JProgressBar();
        jProgressBar4 = new javax.swing.JProgressBar();
        btnAtacar = new javax.swing.JButton();
        lblUsuario1 = new javax.swing.JLabel();
        lblUsuario2 = new javax.swing.JLabel();
        lblUsuario3 = new javax.swing.JLabel();
        lblUsuario4 = new javax.swing.JLabel();
        lblPuntos = new javax.swing.JLabel();
        lblInvocar = new javax.swing.JLabel();
        lblAtacar = new javax.swing.JLabel();
        lblMagia = new javax.swing.JLabel();
        lblMover = new javax.swing.JLabel();
        lblTrampa = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelTerreno.setEnabled(false);
        panelTerreno.setLayout(new java.awt.GridLayout(1, 0));

        btnInvocar.setText("Invocar");
        btnInvocar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInvocarActionPerformed(evt);
            }
        });

        btnFinalizar.setText("Finalizar turno");

        btnMover.setText("Mover ");

        btnLanzar.setText("Lanzar dados");

        btnMagia.setText("Magia");

        btnTrampa.setText("Trampa");

        btnAtacar.setText("Atacar");

        lblUsuario1.setText("jLabel1");

        lblUsuario2.setText("jLabel2");

        lblUsuario3.setText("jLabel3");

        lblUsuario4.setText("jLabel4");

        lblPuntos.setText("Puntos");

        lblInvocar.setText("jLabel7");

        lblAtacar.setText("jLabel8");

        lblMagia.setText("jLabel9");

        lblMover.setText("jLabel10");

        lblTrampa.setText("jLabel11");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelTerreno, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUsuario1)
                            .addComponent(lblUsuario4)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblUsuario2, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblUsuario3)))
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jProgressBar4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(jProgressBar3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(jProgressBar2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnInvocar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblInvocar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAtacar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAtacar))
                    .addComponent(btnFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLanzar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnMagia, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMagia))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(lblPuntos))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnMover, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMover))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnTrampa, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTrampa)))
                .addContainerGap(156, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUsuario1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUsuario2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jProgressBar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUsuario3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jProgressBar4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUsuario4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                        .addComponent(lblPuntos)
                        .addGap(12, 12, 12)
                        .addComponent(btnLanzar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnInvocar)
                            .addComponent(lblInvocar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnMover)
                            .addComponent(lblMover))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAtacar)
                            .addComponent(lblAtacar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTrampa)
                            .addComponent(lblTrampa))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnMagia)
                            .addComponent(lblMagia))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnFinalizar)
                        .addGap(39, 39, 39))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelTerreno, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInvocarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInvocarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInvocarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaBatalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaBatalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaBatalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaBatalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaBatalla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtacar;
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JButton btnInvocar;
    private javax.swing.JButton btnLanzar;
    private javax.swing.JButton btnMagia;
    private javax.swing.JButton btnMover;
    private javax.swing.JButton btnTrampa;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JProgressBar jProgressBar3;
    private javax.swing.JProgressBar jProgressBar4;
    private javax.swing.JLabel lblAtacar;
    private javax.swing.JLabel lblInvocar;
    private javax.swing.JLabel lblMagia;
    private javax.swing.JLabel lblMover;
    private javax.swing.JLabel lblPuntos;
    private javax.swing.JLabel lblTrampa;
    private javax.swing.JLabel lblUsuario1;
    private javax.swing.JLabel lblUsuario2;
    private javax.swing.JLabel lblUsuario3;
    private javax.swing.JLabel lblUsuario4;
    private javax.swing.JPanel panelTerreno;
    // End of variables declaration//GEN-END:variables
    
    public JButton[][] botones = new JButton[15][15];
    
    
    public void agregarListener(ActionListener al,MouseAdapter ml,KeyListener kl){
        for (int i=0;i<15;i++){
            for (int j=0;j<15;j++){
                this.botones[i][j].addActionListener(al);
                this.botones[i][j].addMouseListener(ml);
                
            }
        }
        this.panelTerreno.addMouseWheelListener(ml);
        this.btnInvocar.addActionListener(al);
        this.btnFinalizar.addActionListener(al);
        this.btnLanzar.addActionListener(al);
        this.btnMagia.addActionListener(al);
        this.btnMover.addActionListener(al);
        this.btnTrampa.addActionListener(al);
        this.btnAtacar.addActionListener(al);
        this.addKeyListener(kl);
        //this.setFocusable(true);
        
        
        
        
    }
    public JButton getBtnInvocar(){
        return this.btnInvocar;
    }
    public JButton[][] getBotonesTerreno(){
        return this.botones;
    }
    public JPanel getPanelTerreno(){
        return this.panelTerreno;
    }
    public JButton getBtnFinalizar(){
        return this.btnFinalizar;
    }
    public JButton getBtnLanzar(){
        return this.btnLanzar;
    }
    public JButton getBtnMagia(){
        return this.btnMagia;
    }
    public JButton getBtnMover(){
        return this.btnMover;
    }
    public JButton getBtnTrampa(){
        return this.btnTrampa;
    }
    public JButton getBtnAtacar(){
        return this.btnAtacar;
    }
    
    //GETS DE LOS LABEL DE USUARIOS
    public JLabel getLblUsuario1(){
        return this.lblUsuario1;
    }
    public JLabel getLblUsuario2(){
        return this.lblUsuario2;
    }
    public JLabel getLblUsuario3(){
        return this.lblUsuario3;
    }
    public JLabel getLblUsuario4(){
        return this.lblUsuario4;
    }
    
    //GET DE LOS LABEL DE PUNTOS
    public JLabel getLblInvocar(){
        return this.lblInvocar;
    }
    public JLabel getLblMover(){
        return this.lblMover;
    }
    public JLabel getLblAtacar(){
        return this.lblAtacar;
    }
    public JLabel getLblTrampa(){
        return this.lblTrampa;
    }
    public JLabel getLblMagia(){
        return this.lblMagia;
    }
    
    
    
    
    
       
}
