/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.awt.event.ActionListener;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComboBox;

/**
 *
 * @author Samsung
 */
public class VistaRegistro extends javax.swing.JFrame {

    /**
     * Creates new form VistaRegistro
     */
    public VistaRegistro() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cboxPuzzle = new javax.swing.JComboBox<>();
        btnCancelar = new javax.swing.JButton();
        btnRegistrarse = new javax.swing.JButton();
        lblUsuario = new javax.swing.JLabel();
        lblContaseña = new javax.swing.JLabel();
        lblRContraseña = new javax.swing.JLabel();
        lblJefeTerreno = new javax.swing.JLabel();
        lblPuzzle = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        cboxJefeTerreno = new javax.swing.JComboBox<>();
        lblMsjUsuario = new javax.swing.JLabel();
        lblMsjPwd1 = new javax.swing.JLabel();
        lblMsjPwd2 = new javax.swing.JLabel();
        lblMsjJefeTerreno = new javax.swing.JLabel();
        lblMsjPuzzle = new javax.swing.JLabel();
        txtPwd1 = new javax.swing.JPasswordField();
        txtPwd2 = new javax.swing.JPasswordField();
        lblImagenJT = new javax.swing.JLabel();
        FondoVista = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(985, 614));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cboxPuzzle.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Seleccionar>", "Puzzle 1", "Puzzle 2", "Puzzle 3" }));
        getContentPane().add(cboxPuzzle, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, 103, -1));

        btnCancelar.setText("Cancelar");
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, -1, -1));

        btnRegistrarse.setText("Registrarse");
        getContentPane().add(btnRegistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 360, -1, -1));

        lblUsuario.setText("Usuario");
        getContentPane().add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 88, -1));

        lblContaseña.setText("Contraseña");
        getContentPane().add(lblContaseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 88, -1));

        lblRContraseña.setText("Repita contraseña");
        getContentPane().add(lblRContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, -1, -1));

        lblJefeTerreno.setText("Jefe de terreno");
        getContentPane().add(lblJefeTerreno, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 100, -1));

        lblPuzzle.setText("Puzzle de dados");
        getContentPane().add(lblPuzzle, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, 100, 10));
        getContentPane().add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, 108, -1));

        cboxJefeTerreno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Seleccionar>", "Goku", "Vegeta", "Zolezzi", "Mr.Satan" }));
        cboxJefeTerreno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxJefeTerrenoActionPerformed(evt);
            }
        });
        getContentPane().add(cboxJefeTerreno, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, 103, -1));

        lblMsjUsuario.setForeground(new java.awt.Color(204, 0, 0));
        lblMsjUsuario.setText("*");
        getContentPane().add(lblMsjUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 85, -1, -1));

        lblMsjPwd1.setForeground(new java.awt.Color(204, 0, 0));
        lblMsjPwd1.setText("*");
        getContentPane().add(lblMsjPwd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 135, -1, -1));

        lblMsjPwd2.setForeground(new java.awt.Color(204, 0, 0));
        lblMsjPwd2.setText("*");
        getContentPane().add(lblMsjPwd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 194, -1, -1));

        lblMsjJefeTerreno.setForeground(new java.awt.Color(204, 0, 0));
        lblMsjJefeTerreno.setText("*");
        getContentPane().add(lblMsjJefeTerreno, new org.netbeans.lib.awtextra.AbsoluteConstraints(545, 245, -1, -1));

        lblMsjPuzzle.setForeground(new java.awt.Color(204, 0, 0));
        lblMsjPuzzle.setText("*");
        getContentPane().add(lblMsjPuzzle, new org.netbeans.lib.awtextra.AbsoluteConstraints(545, 295, -1, -1));
        getContentPane().add(txtPwd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, 108, -1));
        getContentPane().add(txtPwd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, 108, -1));
        getContentPane().add(lblImagenJT, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, -10, 480, 270));

        FondoVista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/vistaRegistro2.png"))); // NOI18N
        getContentPane().add(FondoVista, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboxJefeTerrenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxJefeTerrenoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxJefeTerrenoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaRegistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FondoVista;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnRegistrarse;
    private javax.swing.JComboBox<String> cboxJefeTerreno;
    private javax.swing.JComboBox<String> cboxPuzzle;
    private javax.swing.JLabel lblContaseña;
    private javax.swing.JLabel lblImagenJT;
    private javax.swing.JLabel lblJefeTerreno;
    private javax.swing.JLabel lblMsjJefeTerreno;
    private javax.swing.JLabel lblMsjPuzzle;
    private javax.swing.JLabel lblMsjPwd1;
    private javax.swing.JLabel lblMsjPwd2;
    private javax.swing.JLabel lblMsjUsuario;
    private javax.swing.JLabel lblPuzzle;
    private javax.swing.JLabel lblRContraseña;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPasswordField txtPwd1;
    private javax.swing.JPasswordField txtPwd2;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
    
    public String getUsr(){
        return this.txtUsuario.getText();
    }
    public String getPwd1(){
        return this.txtPwd1.getText();
    }
    public String getPwd2(){
        return this.txtPwd2.getText();
    }    
    public JButton getBotonSiguiente(){
        return this.btnRegistrarse;
    }
    public JButton getBotonCancelar(){
        return this.btnCancelar;
    }
    public JComboBox getCboxJefeTerreno(){
       return this.cboxJefeTerreno;
    }
    public JComboBox getCboxPuzzle(){
       return this.cboxPuzzle;
    }
    
    //para obtener lo que esta escrito en los combobox
    public String getItemCboxJefeTerreno(){
       return this.cboxJefeTerreno.getSelectedItem().toString();
    }
    public String getItemCboxPuzzle(){
       return cboxPuzzle.getSelectedItem().toString();
    }
    //para cambiar la imagen de los jefes de terreno
    public void setImagenJefeTerreno(String string){
        if (this.getItemCboxJefeTerreno().equals("<Seleccionar>")==false){
            
        ImageIcon imagen = new ImageIcon (getClass().getResource("/Imagenes/" + string + "Gif.gif"));
        System.out.println("Jefe de terreno seleccionado: "+ string);
        lblImagenJT.setIcon(imagen);
            
        }
        else{
            lblImagenJT.setIcon(null);
            
        }
            
        
    }
    public void setMsjUsuario(String string){
        lblMsjUsuario.setText(string);
    }
    public void setMsjPwd1(String string){
        lblMsjPwd1.setText(string);
    }
    public void setMsjPwd2(String string){
        lblMsjPwd2.setText(string);
    }
    public void setMsjJefeTerreno(String string){
        lblMsjJefeTerreno.setText(string);
    }
    public void setMsjPuzzle(String string){
        lblMsjPuzzle.setText(string);
    }
    
    
    public void agregarListener(ActionListener al){
        this.btnRegistrarse.addActionListener(al);
        this.btnCancelar.addActionListener(al);
        this.cboxJefeTerreno.addActionListener(al);
        this.cboxPuzzle.addActionListener(al);
    }    
}

