/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JComboBox;

/**
 *
 * @author Lizweert
 */
public class VistaModificacionPuzzle extends javax.swing.JFrame {

    /**
     * Creates new form VistaModificacionPuzzle
     */
    public VistaModificacionPuzzle() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CriaturasLvl1CB = new javax.swing.JComboBox<>();
        CriaturasLvl2CB = new javax.swing.JComboBox<>();
        CriaturasLvl3CB = new javax.swing.JComboBox<>();
        CriaturasLvl4CB = new javax.swing.JComboBox<>();
        Agregarlvl1BT = new javax.swing.JButton();
        Agregarlvl2BT = new javax.swing.JButton();
        Agregarlvl3BT = new javax.swing.JButton();
        Agregarlvl4BT = new javax.swing.JButton();
        ListaCriaturasSP = new javax.swing.JScrollPane();
        ListaCriaturas = new javax.swing.JList<>();
        LblNivel1 = new javax.swing.JLabel();
        LblNivel2 = new javax.swing.JLabel();
        LblNivel3 = new javax.swing.JLabel();
        LblNivel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CriaturasLvl1CB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Seleccionar>", "Goku", "Vegeta", "Mr. Popo", "Viru", "Pinky" }));
        getContentPane().add(CriaturasLvl1CB, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 97, 110, -1));

        CriaturasLvl2CB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Seleccionar>", "Mr.Satan", "Critobal", "Seba", "Evelyn", "Nico" }));
        getContentPane().add(CriaturasLvl2CB, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 97, 100, -1));

        CriaturasLvl3CB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Seleccionar>", "Maikel", "Diego", "Rusio", "Pablo", "Javo" }));
        getContentPane().add(CriaturasLvl3CB, new org.netbeans.lib.awtextra.AbsoluteConstraints(428, 97, 100, -1));

        CriaturasLvl4CB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Seleccionar>", "Chapa", "Carlitos", "asdf", "qwerty", "zsdfd" }));
        getContentPane().add(CriaturasLvl4CB, new org.netbeans.lib.awtextra.AbsoluteConstraints(582, 97, 100, -1));

        Agregarlvl1BT.setText("Agregar");
        getContentPane().add(Agregarlvl1BT, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, -1, -1));

        Agregarlvl2BT.setText("Agregar");
        getContentPane().add(Agregarlvl2BT, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, -1, -1));

        Agregarlvl3BT.setText("Agregar");
        getContentPane().add(Agregarlvl3BT, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, -1, -1));

        Agregarlvl4BT.setText("Agregar");
        getContentPane().add(Agregarlvl4BT, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 150, -1, -1));

        ListaCriaturas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "<Vacio>" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        ListaCriaturasSP.setViewportView(ListaCriaturas);

        getContentPane().add(ListaCriaturasSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 340, 130));

        LblNivel1.setText("Nivel 1");
        getContentPane().add(LblNivel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, -1, -1));

        LblNivel2.setText("Nivel 2");
        getContentPane().add(LblNivel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, -1, 20));

        LblNivel3.setText("Nivel 3");
        getContentPane().add(LblNivel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, -1, -1));

        LblNivel4.setText("Nivel 4");
        getContentPane().add(LblNivel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 60, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaModificacionPuzzle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaModificacionPuzzle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaModificacionPuzzle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaModificacionPuzzle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaModificacionPuzzle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregarlvl1BT;
    private javax.swing.JButton Agregarlvl2BT;
    private javax.swing.JButton Agregarlvl3BT;
    private javax.swing.JButton Agregarlvl4BT;
    private javax.swing.JComboBox<String> CriaturasLvl1CB;
    private javax.swing.JComboBox<String> CriaturasLvl2CB;
    private javax.swing.JComboBox<String> CriaturasLvl3CB;
    private javax.swing.JComboBox<String> CriaturasLvl4CB;
    private javax.swing.JLabel LblNivel1;
    private javax.swing.JLabel LblNivel2;
    private javax.swing.JLabel LblNivel3;
    private javax.swing.JLabel LblNivel4;
    private javax.swing.JList<String> ListaCriaturas;
    private javax.swing.JScrollPane ListaCriaturasSP;
    // End of variables declaration//GEN-END:variables

public void agregarListener(ActionListener al){
    this.Agregarlvl1BT.addActionListener(al);
    this.Agregarlvl2BT.addActionListener(al);
    this.Agregarlvl3BT.addActionListener(al);
    this.Agregarlvl4BT.addActionListener(al);  
    this.CriaturasLvl1CB.addActionListener(al);
    this.CriaturasLvl2CB.addActionListener(al);
    this.CriaturasLvl3CB.addActionListener(al);
    this.CriaturasLvl4CB.addActionListener(al);
}
//Obtencion de los Botones
public JButton getAgregarlvl1BT(){
    return this.Agregarlvl1BT;
}
public JButton getAgregarlvl2BT(){
    return this.Agregarlvl2BT;
}
public JButton getAgregarlvl3BT(){
    return this.Agregarlvl3BT;
}
public JButton getAgregarlvl4BT(){
    return this.Agregarlvl4BT;
}



//obtencion de los ComboBox
public String getCBoxCriaturaLvl1(){
    return this.CriaturasLvl1CB.getSelectedItem().toString(); 
}

public String getCBoxCriaturaLvl2(){
    return this.CriaturasLvl2CB.getSelectedItem().toString(); 
}

public String getCBoxCriaturaLvl3(){
    return this.CriaturasLvl3CB.getSelectedItem().toString(); 
}

public String getCBoxCriaturaLvl4(){
    return this.CriaturasLvl4CB.getSelectedItem().toString(); 
}


//obtencion de la lista

public int getListCriatura(){
    return this.ListaCriaturas.getComponentCount();
}
public void setListCriatura(String Criatura){
    this.ListaCriaturas.add(Criatura, this);
}



}
