/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

/**
 *
 * @author Lizweert
 */
public class VistaSeleccionBatalla extends javax.swing.JFrame {

    /**
     * Creates new form VistaSeleccionBatalla
     */
    public VistaSeleccionBatalla() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegistrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        pwd1 = new javax.swing.JPasswordField();
        pwd2 = new javax.swing.JPasswordField();
        pwd3 = new javax.swing.JPasswordField();
        pwd4 = new javax.swing.JPasswordField();
        btnIngresar1 = new javax.swing.JButton();
        btnIngresar2 = new javax.swing.JButton();
        btnIngresar3 = new javax.swing.JButton();
        btnIngresar4 = new javax.swing.JButton();
        cboxRegistrados3 = new javax.swing.JComboBox<>();
        btnJugar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        cboxRegistrados2 = new javax.swing.JComboBox<>();
        cboxRegistrados1 = new javax.swing.JComboBox<>();
        cboxRegistrados4 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        radioJugador1 = new javax.swing.JRadioButton();
        radioPNJ1 = new javax.swing.JRadioButton();
        radioJugador2 = new javax.swing.JRadioButton();
        radioPNJ2 = new javax.swing.JRadioButton();
        radioJugador3 = new javax.swing.JRadioButton();
        radioPNJ3 = new javax.swing.JRadioButton();
        radioJugador4 = new javax.swing.JRadioButton();
        radioPNJ4 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1000, 625));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegistrar.setText("Registrar");
        getContentPane().add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 420, 140, -1));

        jLabel1.setText("Seleccionar jugadores:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, -1, 28));
        getContentPane().add(pwd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 240, 87, -1));
        getContentPane().add(pwd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 270, 87, -1));
        getContentPane().add(pwd3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, 87, -1));
        getContentPane().add(pwd4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, 87, -1));

        btnIngresar1.setText("Ingresar");
        getContentPane().add(btnIngresar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 240, -1, -1));

        btnIngresar2.setText("Ingresar");
        getContentPane().add(btnIngresar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 270, -1, -1));

        btnIngresar3.setText("Ingresar");
        getContentPane().add(btnIngresar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 300, -1, -1));

        btnIngresar4.setText("Ingresar");
        getContentPane().add(btnIngresar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 330, -1, -1));

        cboxRegistrados3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Seleccionar>" }));
        getContentPane().add(cboxRegistrados3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 140, -1));

        btnJugar.setText("Jugar!");
        btnJugar.setEnabled(false);
        getContentPane().add(btnJugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 420, -1, -1));

        btnVolver.setText("Volver");
        getContentPane().add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 420, -1, -1));

        cboxRegistrados2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Seleccionar>" }));
        getContentPane().add(cboxRegistrados2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, 140, -1));

        cboxRegistrados1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Seleccionar>" }));
        getContentPane().add(cboxRegistrados1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, 140, -1));

        cboxRegistrados4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Seleccionar>" }));
        getContentPane().add(cboxRegistrados4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, 140, -1));

        jLabel2.setText("Jugador");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, -1, -1));

        jLabel3.setText("PNJ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, -1, -1));
        getContentPane().add(radioJugador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, -1, -1));
        getContentPane().add(radioPNJ1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, -1, -1));
        getContentPane().add(radioJugador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, -1, -1));
        getContentPane().add(radioPNJ2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, -1, -1));
        getContentPane().add(radioJugador3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, -1, -1));
        getContentPane().add(radioPNJ3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, -1, -1));
        getContentPane().add(radioJugador4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, -1, -1));
        getContentPane().add(radioPNJ4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/2.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaSeleccionBatalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaSeleccionBatalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaSeleccionBatalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaSeleccionBatalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaSeleccionBatalla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar1;
    private javax.swing.JButton btnIngresar2;
    private javax.swing.JButton btnIngresar3;
    private javax.swing.JButton btnIngresar4;
    private javax.swing.JButton btnJugar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cboxRegistrados1;
    private javax.swing.JComboBox<String> cboxRegistrados2;
    private javax.swing.JComboBox<String> cboxRegistrados3;
    private javax.swing.JComboBox<String> cboxRegistrados4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField pwd1;
    private javax.swing.JPasswordField pwd2;
    private javax.swing.JPasswordField pwd3;
    private javax.swing.JPasswordField pwd4;
    private javax.swing.JRadioButton radioJugador1;
    private javax.swing.JRadioButton radioJugador2;
    private javax.swing.JRadioButton radioJugador3;
    private javax.swing.JRadioButton radioJugador4;
    private javax.swing.JRadioButton radioPNJ1;
    private javax.swing.JRadioButton radioPNJ2;
    private javax.swing.JRadioButton radioPNJ3;
    private javax.swing.JRadioButton radioPNJ4;
    // End of variables declaration//GEN-END:variables

    
     public void agregarListener(ActionListener al){

        this.btnRegistrar.addActionListener(al);
        this.btnIngresar1.addActionListener(al);
        this.btnIngresar2.addActionListener(al);
        this.btnIngresar3.addActionListener(al);
        this.btnIngresar4.addActionListener(al);
        this.cboxRegistrados1.addActionListener(al);
        this.cboxRegistrados2.addActionListener(al);
        this.cboxRegistrados3.addActionListener(al);
        this.cboxRegistrados4.addActionListener(al);
        this.btnVolver.addActionListener(al);
        this.btnJugar.addActionListener(al);
        this.radioJugador1.addActionListener(al);
        this.radioJugador2.addActionListener(al);
        this.radioJugador3.addActionListener(al);
        this.radioJugador4.addActionListener(al);
        this.radioPNJ1.addActionListener(al);
        this.radioPNJ2.addActionListener(al);
        this.radioPNJ3.addActionListener(al);
        this.radioPNJ4.addActionListener(al);
        
    }
    

//metodos get de TF
     
     

  
    
//metodos get de las contraseñas


    
    public String getPwdJugador1ST(){
        return this.pwd1.getText();
    }
    public String getPwdJugador2ST(){
        return this.pwd2.getText();
    }
    public String getPwdJugador3ST(){
        return this.pwd3.getText();
    }
    public String getPwdJugador4ST(){
        return this.pwd4.getText();
    }
    public JPasswordField getPwdField1(){
        return this.pwd1;
    }
    public JPasswordField getPwdField2(){
        return this.pwd2;
    }
    public JPasswordField getPwdField3(){
        return this.pwd3;
    }
    public JPasswordField getPwdField4(){
        return this.pwd4;
    }
    
    
    public JButton getBtnJugar(){
        return this.btnJugar;
    }
    public JButton getBtnVolver(){
        return this.btnVolver;
    }
    
    
    public JButton getBtnRegistrar(){
        return this.btnRegistrar;
    }
    public JButton getBtnIngresar1(){
        return this.btnIngresar1;
    }
    public JButton getBtnIngresar2(){
        return this.btnIngresar2;
    }
    public JButton getBtnIngresar3(){
        return this.btnIngresar3;
    }
    public JButton getBtnIngresar4(){
        return this.btnIngresar4;
    }
    
    public JComboBox getCboxRegistrados1(){
        return this.cboxRegistrados1;
    }
    public JComboBox getCboxRegistrados2(){
        return this.cboxRegistrados2;
    }
    public JComboBox getCboxRegistrados3(){
        return this.cboxRegistrados3;
    }
    public JComboBox getCboxRegistrados4(){
        return this.cboxRegistrados4;
    }
    public String getItemCboxRegistrados1(){
        return this.cboxRegistrados1.getSelectedItem().toString();
    }
    public String getItemCboxRegistrados2(){
        return this.cboxRegistrados2.getSelectedItem().toString();
    }
    public String getItemCboxRegistrados3(){
        return this.cboxRegistrados3.getSelectedItem().toString();
    }
    public String getItemCboxRegistrados4(){
        return this.cboxRegistrados4.getSelectedItem().toString();
    }
    
    
    public JRadioButton getRadioJugador1(){
        return this.radioJugador1;
    }
    public JRadioButton getRadioJugador2(){
        return this.radioJugador2;
    }
    public JRadioButton getRadioJugador3(){
        return this.radioJugador3;
    }
    public JRadioButton getRadioJugador4(){
        return this.radioJugador4;
    }
    public JRadioButton getRadioPNJ1(){
        return this.radioPNJ1;
    }
    public JRadioButton getRadioPNJ2(){
        return this.radioPNJ2;
    }
    public JRadioButton getRadioPNJ3(){
        return this.radioPNJ3;
    }
    public JRadioButton getRadioPNJ4(){
        return this.radioPNJ4;
    }
    public void setPwd1(){
    }
    
    //falta agregar los combobox!!!"#!"#
    
   






}
