
package Vistas;
import Modelo.Casilla;
import javax.swing.JPanel;
import java.awt.GridLayout;


public class VistaTablero extends javax.swing.JFrame {
    JPanel Tablero = new JPanel();
    Casilla casilla[] = new Casilla[225];
    
    
    /**
     * Creates new form VistaTablero
     */
    public VistaTablero() {
        super("Batalla");
	setSize(600,600);
	setResizable(false);
	setDefaultCloseOperation(EXIT_ON_CLOSE);
	Tablero.setLayout(new GridLayout(15,15));
	for(int i=0;i<225;i++){
            casilla[i]=new Casilla();
            Tablero.add(casilla[i]);
	}
	add(Tablero);
		
	setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]){
            new VistaTablero();
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
